DailySA/DailySA/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('common/', include('common.urls')),
    path('userstat/', include('userstat.urls')),
]

DailySA/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

DailySA/main/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('result/', views.result, name='result'),
    path('new_post/', views.new_post, name='new_post'),
    path('discussion/', views.discussion, name='discussion'),
    path('<int:discussion_id>/', views.detail, name='detail'),
]

DailySA/userstat/urls.py
from django.urls import path

from . import views

app_name = 'userstat'

urlpatterns = [
    path('mypage/', views.mypage, name='mypage'),
    path('ranking/', views.ranking, name='ranking'),
]

DailySA/common/models.py
from django.db import models

# Create your models here.

DailySA/main/models.py
from django.db import models

# Create your models here.
# 게시글(Post)엔 제목(postname), 내용(contents)이 존재합니다
class Problem(models.Model):
    problem = models.TextField()
    options = models.TextField()
    answer = models.TextField()

class Discussion(models.Model):
    postname = models.CharField(max_length=200)
    content = models.TextField()
    problem_id = models.ForeignKey('Problem', on_delete=models.CASCADE)

DailySA/userstat/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Solved(models.Model):
    problem_id = models.ForeignKey('main.Problem', on_delete=models.CASCADE)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)

DailySA/common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email")

DailySA/common/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from common.forms import UserForm


def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)  # 사용자 인증
            login(request, user)  # 로그인
            return redirect('index')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})

DailySA/main/views.py
from django.shortcuts import render, redirect
import random
from .models import Problem, Discussion
from userstat.models import Solved

# Create your views here.
def index(request):
    parm = request.GET.get("pnum", "")
    print(parm)
    if parm == "" :
        items = list(Problem.objects.all())
        ran = random.choice(items)
    else :
        ran = Problem.objects.get(pk=parm)
    pnum = ran.pk
    problem = ran.problem
    options = ran.options.split("\n")
    random.shuffle(options)
    answer = ran.answer

    return render(request,'main/index.html', {'pnum': pnum, 'problem': problem, 'o1': options[0], 'o2': options[1], 'o3': options[2], 'o4': options[3], 'answer': answer})

def result(request):
    select = request.GET['select'].strip()
    answer = request.GET['answer'].strip()
    user = request.user
    pnum = request.GET['pnum']
    problem = Problem.objects.get(pk=pnum)
    if select == answer and user.username != '':
        user_solved = Solved.objects.filter(user_id=user)
        switch = 0
        for suser in user_solved :
            if suser.problem_id == Problem.objects.get(pk=pnum) :
                switch = 1
                break
        if switch == 0 :
            tsolved = Solved(problem_id=Problem.objects.get(pk=pnum), user_id=user)
            tsolved.save()
        return render(request, 'main/correct.html')
    elif select == answer :
        return render(request, 'main/correct.html')
    else :
        question = problem.problem
        options = problem.options.split("\n")
        return render(request, 'main/false.html', {'pnum': pnum, 'problem': question, 'o1': options[0], 'o2': options[1], 'o3': options[2], 'o4': options[3], 'answer': answer, 'select': select})

def new_post(request):
    if request.method == 'POST':
        pnum = request.POST.get('pnum')
        new_discussion=Discussion(
            postname=request.POST.get('postname'),
            content=request.POST.get('content'),
            problem_id=Problem.objects.get(pk=pnum)
            )
        new_discussion.save()
        return redirect('discussion')
    else :
        pnum = request.GET['pnum']
    return render(request, 'main/new_post.html', {'pnum': pnum})

def discussion(request):
    discussions = Discussion.objects.all()
    return render(request, 'main/discussion.html', {'discussions': discussions})

def detail(request, discussion_id):
    discussion = Discussion.objects.get(pk=discussion_id)
    postname = discussion.postname
    content = discussion.content
    problem_id = discussion.problem_id.pk
    return render(request, 'main/detail.html', {'postname': postname, 'content': content, 'problem_id': problem_id})

DailySA/userstat/views.py
from django.shortcuts import render
from .models import Solved
from main.models import Problem
from django.contrib.auth.models import User

# Create your views here.
def mypage(request):
    user = request.user
    user_solved = Solved.objects.filter(user_id=user)
    problems = Problem.objects.all()
    n = 0
    pklst = []
    for i in user_solved :
        pklst.append(i.problem_id.pk)
        n += 1
    nn = 0
    npklst = []
    for i in problems :
        if i.pk  not in pklst :
            npklst.append(i.pk)
            nn += 1
    return render(request, 'userstat/mypage.html', {'nsolved': n, 'pklst': pklst, 'nnsolved': nn, 'npklst': npklst})

def ranking(request):
    users = User.objects.all()
    solutions = Solved.objects.all()
    rank = {}
    for user in users :
        rank[user.username] = 0
    for solution in solutions :
        rank[solution.user_id.username] += 1
    rank = dict(sorted(rank.items(), key=lambda x: x[1], reverse=True))    
    rank = [rank]
    return render(request, 'userstat/ranking.html', {'rank': rank})

DailySA/DailySA/templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'main/style.css' %}">
    <title>Hello, main!</title>
</head>
<body>
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'index' %}">main</a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a> </li>
                    <li><a class="nav-link" href="{% url 'userstat:mypage' %}">마이페이지</a></li>
                    {% else %}
                    <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                    {% endif %}
                </li>
                <li>
                    {% if not user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:signup' %}">회원가입</a>
                    {% endif %}
                </li>
                <li>
                    <a class="nav-link" href="{% url 'userstat:ranking' %}">랭킹</a>
                </li>
                <li>
                    <a class="nav-link" href="{% url 'discussion' %}">질문</a>
                </li>
                <li>
                    <a class="nav-link" href="https://github.com/StitCJ/DailySA">GitHub</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
</body>
</html>

DailySA/DailySA/templates/common/login.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <form method="post" action="{% url 'common:login' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">로그인</button>
    </form>
</div>
{% endblock %}

DailySA/DailySA/templates/common/signup.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <form method="post" action="{% url 'common:signup' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="username">사용자 이름</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1"
                   value="{{ form.password1.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2"
                   value="{{ form.password2.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="email">이메일</label>
            <input type="text" class="form-control" name="email" id="email"
                   value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">생성하기</button>
    </form>
</div>
{% endblock %}

DailySA/DailySA/templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

DailySA/DailySA/templates/result_footer.html
<style>
	form {
		display: inline;
	}
</style>
<form action="{% url 'index' %}">
	<input type="submit" value="다른문제" class="btn btn-primary">
</form>
{% if user.is_authenticated %}
<form action="{% url 'new_post' %}">
	<input type="hidden" name="pnum" value="{{pnum}}">
	<input type="submit" value="질문하기" class="btn btn-danger">
{% endif %}
</form>

DailySA/DailySA/templates/userstat/mypage.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <br>
    내가 푼 문제 개수: {{ nsolved }}
    <br>
    <br>
    <form action="{% url 'index' %}" method="get">
    {% csrf_token %}
    {% for i in pklst %}
    <button class="btn btn-primary" type="submit" name="pnum" value="{{ i }}" style="margin-top: 10px">{{ i }}</button>
    {% endfor %}
    </form>

    <br>
    내가 풀지 않은 문제 개수: {{ nnsolved }}
    <br>
    <br>
    <form action="{% url 'index' %}" method="get">
    {% csrf_token %}
    {% for i in npklst %}
    <button class="btn btn-danger" type="submit" name="pnum" value="{{ i }}" style="margin-top: 10px">{{ i }}</button>
    {% endfor %}
    </form>
</div>
{% endblock %}

DailySA/DailySA/templates/userstat/ranking.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <br>
        <style>
            tbody>tr {
              counter-increment: aaa;
            }
            tbody>tr>td:first-child:before {
              content: counter(aaa) " ";
            }
        </style>
        <table class="table counter">
            <thead>
                <tr>
                    <th> 랭킹 </th>
                    <th> 아이디 </th>
                    <th> 푼 문제 </th>
                </tr>
            </thead>
            <tbody>
            {% for i in rank %}
                {% for key, value in i.items %}
                <tr>
                    <td></td>
                    <td>{{ key }} </td>
                    <td>{{ value }} </td>
                </tr>
                {% endfor %}
            {% endfor %}
            </tbody>
        </table>
</div>
{% endblock %}

DailySA/main/templates/main/correct.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
        <br>
        {{userpk}}
        정답입니다!
        <br>
        <br>
        {% include 'result_footer.html' %}
</div>

{% endblock %}

DailySA/main/templates/main/detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <h2 class="border-bottom py-2">{{ postname }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2">
                    {{ question.create_date }}
                </div>
            </div>
        </div>
    </div>

{% endblock %}

DailySA/main/templates/main/discussion.html
{% extends 'base.html' %}
{% block content %}
<style>
    td {
        vertical-align: middle;
    }
</style>
<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="table-dark">
            <th>번호</th>
            <th>제목</th>
            <th>문제 번호</th>
        </tr>
        </thead>
        <tbody>
        {% if discussions %}
        {% for discussion in discussions %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>
                <a href="{% url 'detail' discussion.pk %}">{{ discussion.postname }}</a>
            </td>
            <td>
                <form action="{% url 'index' %}" method="get">
                    {% csrf_token %}
                <button class="btn btn-primary" type="submit" name="pnum" value="{{ discussion.problem_id.pk }}" style="margin-top: 10px">{{ discussion.problem_id.pk }}</button>
            </td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
</div>
{% endblock %}

DailySA/main/templates/main/false.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <br> <div><b>NO.{{pnum}}</b> {{problem}}</div> <br>
<div>
<label>1. {{o1}}</label> <br>
<label>2. {{o2}}</label> <br>
<label>3. {{o3}}</label> <br>
<label>4. {{o4}}</label> <br>
</div> <br>
	정답: {{answer}} <br>
	오답: {{select}} <br><br>

{% include 'result_footer.html' %}
{% endblock %}

DailySA/main/templates/main/index.html
{% extends 'base.html' %}
{% block content %}
<form action= "{% url 'result' %}" method="get">
    <div class="container my-3">
        <br>
        <div clas="card my-3"><b>NO.{{pnum}}</b> {{problem}}</div> <br>
    <div class="list-group">
    <label><input class="form-check-input" type="radio" name="select" value="{{o1}}"> 1. {{o1}}</label> <br>
    <label><input class="form-check-input" type="radio" name="select" value="{{o2}}"> 2. {{o2}}</label> <br>
    <label><input class="form-check-input" type="radio" name="select" value="{{o3}}"> 3. {{o3}}</label> <br>
    <label><input class="form-check-input" type="radio" name="select" value="{{o4}}"> 4. {{o4}}</label> <br>
    </div> <br>
    <input type="hidden" name="answer" value="{{answer}}">
    <input type="hidden" name="pnum" value="{{pnum}}">
    <input type="submit" class="btn btn-primary">
    </div>
</form>
{% endblock %}

DailySA/main/templates/main/new_post.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
<form action="{% url 'new_post' %}" method="POST">
    {% csrf_token %}
    <br>제목<br>
    <input type="text" name="postname" class="form-control"><br>
    내용<br>
    <textarea rows="10" cols="50" name="content" class="form-control"></textarea><br>
    <input type="hidden" name="pnum" value="{{pnum}}">
    <input type="submit" value="글쓰기">
</form>
</div>
{% endblock %}